block-beta
   block
   a
   b
   c
   d
   end
   block
   columns 4
   oa["pitch lock 1"]
   ob["quantize 1"]
   oc["phrase 1"]
   od["phrase 1"]
   oe
   of
   og
   oh
   oi
   oj
   ok
   ol
   om
   on
   oo
   op
   end
